import type { GameConfig } from "./game/index.ts";

/** Bộ nội dung tối thiểu cho test của rules, độc lập với @tentides/content. */
export const testConfig: GameConfig = {
  incidentChance: 0,
  items: [
    { id: "rope", name: "Dây thừng", size: { w: 2, h: 3 }, weightKg: 2, price: 12, tags: ["tool"] },
    { id: "shovel", name: "Xẻng", size: { w: 1, h: 6 }, weightKg: 2.5, price: 12, tags: ["tool", "dig"] },
    { id: "lantern", name: "Đèn dầu", size: { w: 2, h: 2 }, weightKg: 1, price: 14, tags: ["light"] },
    { id: "rum", name: "Rượu rum", size: { w: 1, h: 3 }, weightKg: 1, price: 8, tags: ["luxury"] },
    { id: "old_map", name: "Bản đồ cũ", size: { w: 2, h: 2 }, weightKg: 0.2, price: 18, tags: ["clue"] },
    { id: "hardtack", name: "Lương khô", size: { w: 1, h: 2 }, weightKg: 0.5, price: 4, tags: ["food"] },
    { id: "first_aid_kit", name: "Bộ sơ cứu", size: { w: 3, h: 2 }, weightKg: 1, price: 16, tags: ["medical"] },
    { id: "flintlock", name: "Súng kíp", size: { w: 1, h: 5 }, weightKg: 3, price: 30, tags: ["weapon"] },
    { id: "amulet", name: "Bùa hộ mệnh", size: { w: 1, h: 1 }, weightKg: 0.1, price: 5, tags: ["mystery"] },
    { id: "hammer", name: "Búa", size: { w: 1, h: 3 }, weightKg: 1.5, price: 10, tags: ["tool"] },
    { id: "gunpowder", name: "Thuốc súng", size: { w: 2, h: 2 }, weightKg: 1, price: 12, tags: ["explosive"] },
    { id: "matches", name: "Diêm", size: { w: 1, h: 1 }, weightKg: 0.1, price: 3, tags: ["fire"] },
  ],
  treasureSites: [{ id: "site_a" }, { id: "site_b" }],
  anchors: [
    { id: "grove_1", type: "grove", zone: "beach" },
    { id: "grove_2", type: "grove", zone: "beach" },
    { id: "cave_1", type: "tunnel", zone: "cave" },
  ],
  cards: [
    {
      id: "coconut",
      title: "Cây dừa",
      intro: "Một cây dừa trĩu quả.",
      acts: [1, 2, 3],
      anchorType: "grove",
      choices: [
        {
          id: "climb",
          label: "Trèo lên",
          check: { stat: "dexterity", dc: 10, itemBonus: { rope: 2 } },
          onSuccess: { food: 2 },
          onFail: { hp: -10 },
          successText: "Hái được dừa.",
          failText: "Trượt chân ngã.",
        },
        {
          id: "shake",
          label: "Rung cây",
          check: { stat: "strength", dc: 12 },
          onSuccess: { food: 1 },
          onFail: { morale: -5 },
          successText: "Rơi một quả.",
          failText: "Không ăn thua.",
        },
      ],
      narrativeHooks: [],
    },
    {
      id: "deadly",
      title: "Vực sâu",
      intro: "Một vực thẳm.",
      acts: [1, 2, 3],
      anchorType: "tunnel",
      choices: [
        {
          id: "jump",
          label: "Nhảy",
          check: { stat: "nerve", dc: 99 },
          onSuccess: {},
          onFail: { hp: -999, loseRandomItem: 1 },
          successText: "",
          failText: "Rơi xuống.",
        },
        {
          id: "map",
          label: "Tìm đường",
          check: { stat: "intellect", dc: 1 },
          onSuccess: { treasure: 60, setFlag: "found_path" },
          onFail: {},
          successText: "Thấy lối đi.",
          failText: "",
        },
      ],
      sceneState: { onAny: "tunnel_explored" },
      narrativeHooks: [],
    },
  ],
};
